### ISSUE TITLE
Port to Sponge

### ISSUE THREAD

**Issue by CrystalMare** [Slikey/EffectLib#22]
Will this library ever be ported/supported in sponge?

Currently Sponge is under heavy development, but once it matures it should offer the ability to add effects as well.

**Comment by NathanWolf** [comment]
Hm, it probably wouldn't be that hard to do since there is just the one NMS packet call, and I imagine the rest would be search+replace for Location and Entity type classes.

Personally I don't have plans for Sponge support, though. That may change in the future, but my own projects are a little too big and old to think about porting.

**Comment by CrystalMare** [comment]
Since @iarepandemonium is working on a plugin that heavily depends on this, maybe when we start using Sponge I'd end up making a PR for a port

**Comment by NathanWolf** [comment]
That would be awesome if you do! :)

It'd probably be best for that to live as a separate branch, so we can maintain and build both of them. I'll go ahead and make a sponge branch now, so you have something to PR to if you ever get there.

**Comment by CrystalMare** [comment]
Very well

**Comment by ryantheleach** [comment]
I'd just like to mention https://github.com/ryantheleach/EffectLib/tree/sponge2

It's unfinished and was more a challenge to try to see what is blocking / would be needing to be changed to be more platform independent.

I didn't get super far until needing to swap projects due to unrelated reasons.

By far the biggest painpoints are the need of a mutable vectors for DynamicLocation and making sure that appropriate copying takes place or the possible replacement by immutable vectors.

As well as migrating between bukkit locations and sponge translations.

If you want to have a core that is platform independent, these seem to be the major points. 

The next one that I havn't even started to touch is configuration. The current EffectManager is very tightly coupled to bukkits ConfigurationSection.

**Comment by NathanWolf** [comment]
So yeah this is probably never happening.
