### ISSUE TITLE
Maven repository down

### ISSUE THREAD

**Issue by JeromSar** [Slikey/EffectLib#43]
Hey,

The http://maven.elmakers.com/repository/ repository appears to be down.

Is it possible possible to publish to the Central Repository so EffectLib has (near) guaranteed availability?

Jerom

**Comment by NathanWolf** [comment]
No idea how to do that.

**Comment by ampayne2** [comment]
👍 this library deserves a working maven repo!

**Comment by JeromSar** [comment]
I managed to continue with JitPack, a service which proxies Git repositories as Maven repositories:
https://jitpack.io/#Slikey/EffectLib

However, this is a workaround, the Central Repository would be a better long-term repository.

**Comment by NathanWolf** [comment]
You are welcome to submit the jar to a central repository if that's something you know how to do.

**Comment by Kainzo** [comment]
@NathanWolf is this something we can add to our Herocraft Nexus?

**Comment by NathanWolf** [comment]
@Kainzo if you want, that'd be awesome!

I do have it in my Maven repo, but it's down (dead HD) which is why everyone's complaining.

I think a central repo would be a good idea, too, but not really sure what's involved there. The more repos this is in the better, though- it has very minimal dependencies so it shouldn't be hard to add. It also doesn't change a whole lot at this point, mostly only when new particles are added to MC.

**Comment by Kainzo** [comment]
@mung3r
Going to tag him since he manages the nexus repo.

**Comment by mung3r** [comment]
I'll add the 5.4 jar to our nexus

**Comment by NathanWolf** [comment]
Thank you!

**Comment by Kainzo** [comment]
http://nexus.hc.to/content/repositories/thirdparty/
<3

**Comment by JeromSar** [comment]
@Kainzo 👍
