### ISSUE TITLE
Equation Effect Race Condition

### ISSUE THREAD

**Issue by jye110** [Slikey/EffectLib#63]
The Equation Effect share the EquationTransform in Equation Store. When two effects with same equation are running concurrently, both are modifying the variables in same transform and result wrong location. Just creating new EquationTransform instead of fetching from Equation Store could fix this.
![image](https://user-images.githubusercontent.com/59116993/113266994-b3865700-928a-11eb-9ea6-96ad90c4f474.png)

**Comment by NathanWolf** [comment]
Oops, yup you are right- this is because EffectLib is multithreaded.

I will look into fixing this, thanks for the report!

I will be finding a good place to synchronize though, creating new transforms (x3 or x6) for every effect for every tick would be very inefficient, but thank you for the suggestion!

**Comment by NathanWolf** [comment]
This is now fixed in the latest dev build of EffectLib, which you can download here:

https://jenkins.elmakers.com/job/EffectLib/

If you get a chance to test it and let me know if you think the problem is fixed, I would appreciate it!

Thank you for the report.

**Comment by jye110** [comment]
Nice! It works well
